version: '3.9'
services:
  flask-eureka:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      STOCK_API_KEY:
      STOCK_API_URL:
      DB_NAME:
      DB_CONN_STRING:
      FLASK_ENV:
