version: '3.9'
volumes:
  mongodb:
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  flask-eureka:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      STOCK_API_KEY:
      STOCK_API_URL:
      DB_NAME:
      DB_CONN_STRING: mongodb://mongo
      FLASK_ENV:
    depends_on:
      - mongo
